# Generated by Django 4.2.11 on 2026-01-16 13:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('partner', 'Partenaire')], default='client', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('tva_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('partner_type', models.CharField(blank=True, max_length=50)),
                ('coverage_radius', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('postal_codes', models.TextField(help_text='Codes postaux séparés par des virgules')),
                ('quantity', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('CREATED', 'Créée'), ('ASSIGNED', 'Attribuée à partenaire'), ('IN_PRINTING', 'En impression'), ('PRINTED', 'Imprimée'), ('IN_DISTRIBUTION', 'En distribution'), ('DELIVERED', 'Livrée'), ('FINISHED', 'Terminée')], default='CREATED', max_length=20)),
                ('printing_status', models.CharField(choices=[('NOT_SENT', 'Non envoyé'), ('SENT_TO_PRINT', "Envoyé à l'impression"), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], default='NOT_SENT', max_length=20)),
                ('special_request', models.TextField(blank=True, help_text="Demandes spéciales pour l'impression", null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faces', models.IntegerField(default=1, help_text='Nombre de faces (1 ou 2)')),
                ('payment_required', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('secure_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('custom_card', models.FileField(blank=True, null=True, upload_to='custom_cards/')),
                ('use_custom_card', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('coverage_radius', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Créé'), ('ASSIGNED', 'Assigné'), ('IN_PRINTING', 'En impression'), ('PRINTED', 'Imprimé'), ('DELIVERED', 'Livré')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('campaigns', models.ManyToManyField(related_name='print_batches', to='api.campaign')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.partner')),
            ],
            options={
                'verbose_name': "Batch d'impression",
                'verbose_name_plural': "Batchs d'impression",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('SHIPPED', 'Expédié')], default='PENDING', max_length=20)),
                ('print_file', models.FileField(blank=True, null=True, upload_to='print_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_order', to='api.printbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_proofs/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.campaign')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Création'), ('STATUS_CHANGE', 'Changement de statut'), ('PARTNER_ASSIGNED', 'Partenaire assigné'), ('ADDED_TO_BATCH', 'Ajouté à un batch'), ('BATCH_CREATED', 'Batch créé'), ('SENT_TO_PRINT', "Envoyé à l'impression"), ('DESIGN_UPDATED', 'Design mis à jour'), ('PROOF_UPLOADED', 'Preuve uploadée'), ('COMMENT', 'Commentaire')], max_length=50)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.printbatch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.campaign')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('company_postal_code', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='designs/logos/')),
                ('template', models.CharField(choices=[('template_1', 'Template 1'), ('template_2', 'Template 2'), ('template_3', 'Template 3'), ('template_4', 'Template 4'), ('template_5', 'Template 5'), ('template_6', 'Template 6'), ('template_7', 'Template 7'), ('template_8', 'Template 8'), ('template_9', 'Template 9'), ('template_10', 'Template 10'), ('template_11', 'Template 11'), ('template_12', 'Template 12'), ('template_13', 'Template 13'), ('template_14', 'Template 14'), ('template_15', 'Template 15'), ('template_16', 'Template 16'), ('template_17', 'Template 17'), ('template_18', 'Template 18'), ('template_19', 'Template 19'), ('template_20', 'Template 20')], default='template_1', max_length=20)),
                ('accent_color', models.CharField(default='#3498DB', max_length=7)),
                ('contact_method', models.CharField(choices=[('email', 'Email seulement'), ('whatsapp', 'WhatsApp seulement'), ('both', 'Email et WhatsApp')], default='email', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='api.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.partner'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='api_loginat_email_eab493_idx'), models.Index(fields=['ip_address', 'timestamp'], name='api_loginat_ip_addr_af145a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['order_number'], name='api_campaig_order_n_d4795d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='api_campaig_status_2812a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['printing_status'], name='api_campaig_printin_c4c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['client', 'created_at'], name='api_campaig_client__684449_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['postal_codes'], name='api_campaig_postal__92c4dc_idx'),
        ),
    ]
