# Generated by Django 4.2.11 on 2026-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
